language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
